#name: bebshar_poristhiti
#description: "A new Flutter project."
#
#publish_to: 'none'
#version: 1.0.0+1
#
#environment:
#  sdk: ^3.5.3
#
#dependencies:
#  flutter:
#    sdk: flutter
#  firebase_core: ^3.6.0
#  firebase_auth: ^5.3.1
#  cloud_firestore: ^5.4.4
#  fl_chart: ^0.69.0
#  flutter_secure_storage: ^9.2.2
#  firebase_storage: ^12.3.3
#  fluttertoast: ^8.2.8
#  flutter_native_splash: ^2.4.2
#  intl: ^0.19.0
#  image_picker: ^1.1.2
#  shared_preferences: ^2.3.2
#  url_launcher: ^6.3.1
#  provider: ^6.1.2
#  cupertino_icons: ^1.0.8
#  image_picker_for_web: ^3.0.5
#  expressions: ^0.2.5+2
#  pdf: ^3.11.1
#  image: ^4.3.0
#  flutter_svg: ^2.0.10+1
#  path_provider: ^2.1.4
#  open_file: ^3.5.9
#  google_fonts: ^5.0.0
#  flutter_font_picker: ^1.4.0
#  firebase_messaging: ^15.1.3
#  logger: ^2.4.0
#  flutter_local_notifications: ^17.2.3
#  stream_transform: ^2.1.0
#  path: ^1.9.0
#  dartz: ^0.10.1
#  excel: ^4.0.6
#  file_picker: ^8.1.3
#  font_awesome_flutter: ^10.7.0
#  lottie: ^3.1.3
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^5.0.0
#  flutter_launcher_icons: ^0.14.1
#
#flutter:
#  uses-material-design: true
#
#  assets:
#    - assets/error.jpg
#    - assets/image1.jpg
#    - assets/image2.jpg
#    - assets/image3.jpg
#    - assets/image4.jpg
#    - assets/login_pic.jpg
##    - assets/background.jpg
#    - assets/icon/icon.png
##    - assets/icon/sale.png
##    - assets/icon/sale.png
#    - assets/icon/analytics_2518147.png
#    - assets/icon/book_5011389.png
#    - assets/icon/book_8998090.png
#    - assets/icon/cash-register_3258571.png
#    - assets/icon/logistic-distribution_14669990.png
#    - assets/icon/shopping-cart_6145556.png
#    - assets/icon/transaction_6145523.png
#    - assets/icon/wallet_1747291.png
#    - assets/icon/due.png
#    - assets/lightning-frame.jpg
#
#flutter_launcher_icons:
#  android: true
#  image_path: "assets/icon/icon.png"
#  min_sdk_android: 21
#
#flutter_native_splash:
#  color: "#ffffff" # Background color
#  image: assets/icon/icon.png # Your splash image
#  android: {
#    fullscreen: true # Set to true to make it fullscreen on Android
#  }
#///////////////////////////////////////////////////////////////////////////
name: bebshar_poristhiti
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fl_chart: ^0.69.0
  flutter_secure_storage: ^9.2.2
  firebase_storage: ^12.3.3
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  image_picker_for_web: ^3.0.5
  expressions: ^0.2.5+2
  pdf: ^3.11.1
  image: ^4.3.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.4
  open_file: ^3.5.9
  google_fonts: ^5.0.0
  flutter_font_picker: ^1.4.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  stream_transform: ^2.1.0
  path: ^1.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/error.jpg
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/login_pic.jpg
#    - assets/background.jpg
    - assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21